### ISSUE TITLE
Red Border box and null value

### ISSUE THREAD

**Issue by DecoyOtter** [DynamicsNinja/PCF-Prefix-Suffix-Control#1]
Hi,

Couple questions.

Any reason there's a red border box around the field area?
![firefox_dkfvAXqdYK](https://user-images.githubusercontent.com/46342392/67645359-6b1f8700-f97c-11e9-990a-93ceb33d17eb.png)

And, is there a way for it to display no value, instead of 'null' when the field is empty?
![firefox_0Cq2RmhoJp](https://user-images.githubusercontent.com/46342392/67645365-78d50c80-f97c-11e9-9ecc-11b13c9ec452.png)

Thanks!

**Comment by DynamicsNinja** [comment]
I'm not sure why you get the red border around the textbox. Can you share the field configuration so I can reproduce the issue?

Null value on the empty field is definitely a bug and I will fix that as soon as possible.

**Comment by DecoyOtter** [comment]
Sure, here is the field information:
![image](https://user-images.githubusercontent.com/46342392/67727807-ec3f5280-fa3e-11e9-950f-a0cceda2bf6a.png)

And here is the control info
![image](https://user-images.githubusercontent.com/46342392/67727829-05e09a00-fa3f-11e9-9c64-69473fca1277.png)

**Comment by DecoyOtter** [comment]
Looks like your latest 1.1.4 update has resolved both these issues.

Thanks very much!

**Comment by DynamicsNinja** [comment]
I'm glad that your issues are resolved.

**Comment by shytikov** [comment]
I'm still getting red border. Downloaded the last release. Appears on longer values. Or overall incorrect values.... It might be platform feature, I believe... But still I don't get it when I'm using regular control.
